--- name:default
# Opening of the beam along the device's Z direction
beam_height:
  rad: 35.deg
# Opening of the beam orthogonal to the device's Z direction
beam_width:
  rad: 3.deg
# Number of Bins
bin_count: 500
# Enable/disable ping pong scanning mode
continuous: true
# Enable underwater signal attenuation effect
enable_attenuation: true
# Enable reverberation effect in acoustic image
enable_reverberation: true
# Enable speckle noise in acoustic image
enable_speckle_noise: true
# Gain of the sonar (0.0 - 1.0)
gain: 0.5
# Left limit angle
left_limit:
  rad: -180.deg
# Step angle size
motor_step:
  rad: 1.8.deg
# Range of the sonar in meters (1.0 - 150.0)
range: 20.0
# Right limit angle
right_limit:
  rad: 179.9.deg
# Write shader image
write_shader_image: false
